import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/utils/SessionProvider"; // Ensure this path is correct based on your project structure
import NavbarSwitcher from "@/components/NavbarSwitcher";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NextPoll",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <NavbarSwitcher />
          <div className="mx-auto max-w-5xl text-2xl gap-2 mb-10">
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
